// src/svelte/src/pages/Chapter06.svelte
<script>
  import { useSendCode } from '../hooks/useSendCode';

  let count = 0;

  $: doubleCount = count * 2;

  const updateCount = () => {
    count++;
  };

  useSendCode('06');
</script>

<section>
  <h1>第六章 —— computed</h1>
  <button class="w-auto h-auto p-1 border" on:click={updateCount}> +1 </button>
  <span>
    {count}的2倍是：{doubleCount}
  </span>
</section>

// src/react/src/pages/Chapter06.jsx
import { useState, useMemo } from "react";
import { useSendCode } from '../hooks/useSendCode';

export default function Page() {
  const [count, setCount] = useState(0);

  const doubleCount = useMemo(() => {
    return count * 2;
  }, [count]);

  const updateCount = () => {
    setCount(count + 1);
  };

  useSendCode('06');

  return (
    <section>
      <h1>第六章 —— computed</h1>
      <button
        className="w-auto h-auto p-1 border"
        onClick={updateCount}
      >
        +1
      </button>
      <span>
        {count}的2倍是：{doubleCount}
      </span>
    </section>
  );
}
