// src/vue/src/pages/Chapter09.vue
<template>
  <section>
    <h1>第九章 —— for</h1>
    <ul>
      <li v-for="(item, index) in list" :key="index">item - {{ item }}</li>
    </ul>
  </section>
</template>

<script setup>
import { reactive } from "vue";
import { useSendCode } from '../hooks/useSendCode';

const list = reactive([1, 2, 3]);
useSendCode('09');
</script>

// src/react/src/pages/Chapter09.jsx
import { useState } from "react";
import { useSendCode } from '../hooks/useSendCode';

export default function Page() {
  const [list] = useState([1, 2, 3]);

  useSendCode('09');
  return (
    <section>
      <h1>第九章 —— for</h1>
      <ul>
        {list.map((item, index) => {
          return <li key={index}>item - {item}</li>;
        })}
      </ul>
    </section>
  );
}
