// src/svelte/src/App.svelte
<script>
  import { Router, Route } from 'svelte-routing';
  import { routes } from './router';
  import { qiankunWindow } from 'vite-plugin-qiankun/dist/helper'

  export let url = ""
</script>

<main class="text-svelte">
  <Router {url} basepath={qiankunWindow.__POWERED_BY_QIANKUN__ ? '/svelte' : '/'}>
    {#each routes as route}
      <Route path={route.path} component={route.component} />
    {/each}
  </Router>
</main>

<!-- <style src="./app.css">

</style> -->

// src/solid/src/App.jsx
import { Router } from "@solidjs/router";
import { routes } from "./router";
import { qiankunWindow } from "vite-plugin-qiankun/dist/helper";

function App() {
  return (
    <div className="text-solid">
      <Router base={qiankunWindow.__POWERED_BY_QIANKUN__ ? "/solid" : ""}>
        {routes}
      </Router>
    </div>
  );
}

export default App;
