// src/solid/src/router/index.jsx
import { lazy } from 'solid-js';

export const routes = [
  {
    path: "/chapter01",
    component: lazy(() => import("../pages/Chapter01")),
  },
  {
    path: '/chapter02',
    component: lazy(() => import("../pages/Chapter02")),
  },
  {
    path: '/chapter03',
    component: lazy(() => import("../pages/Chapter03")),
  },
  {
    path: '/chapter05',
    component: lazy(() => import("../pages/Chapter05")),
  }
]

// src/react/src/router/index.jsx
import { createBrowserRouter } from "react-router-dom";
import { qiankunWindow } from 'vite-plugin-qiankun/dist/helper'

import Layout from "../Layout.jsx";
import Chapter01 from "../pages/Chapter01.jsx";
import Chapter02 from "../pages/Chapter02.jsx";
import Chapter03 from "../pages/Chapter03.jsx";
import Chapter04 from "../pages/Chapter04.jsx";
import Chapter05 from "../pages/Chapter05.jsx";


export const router = createBrowserRouter([
  {
    path: "/",
    Component: Layout,
    children: [
      {
        path: "/chapter01",
        Component: Chapter01,
      },
      {
        path: "/chapter02",
        Component: Chapter02,
      },
      {
        path: "/chapter03",
        Component: Chapter03,
      },
      {
        path: "/chapter04",
        Component: Chapter04,
      },
      {
        path: "/chapter05",
        Component: Chapter05
      }
    ],
  },
], {
  basename: qiankunWindow.__POWERED_BY_QIANKUN__ ? '/react' : ''
});
