// src/react/src/pages/Chapter02.jsx
import { useState } from "react";
import { useSendCode } from '../hooks/useSendCode';

export default function Page() {
  const [count, setCount] = useState(0);

  const updateCount = () => {
    setCount(count + 1);
  };

  useSendCode('02');

  return (
    <section>
      <h1>第二章 —— 方法</h1>
      <div>
        count: {count}
        <button className="w-16 h-10 rounded-sm flex items-center justify-center border" onClick={updateCount}>+1</button>
      </div>
    </section>
  );
}

// src/solid/src/pages/Chapter02.jsx
import { createSignal } from "solid-js";
import { useSendCode } from '../hooks/useSendCode';

export default function Page() {
  const [count, setCount] = createSignal(0);

  const updateCount = () => {
    setCount(count() + 1);
  };

  useSendCode('02');

  return (
    <section>
      <h1>第二章 —— 方法</h1>
      <div>
        count: {count()}
        <button className="w-16 h-10 rounded-sm flex items-center justify-center border" onClick={updateCount}>+1</button>
      </div>
    </section>
  );
}
