// src/solid/src/hooks/useSendCode.js
import { createEffect } from 'solid-js';
import {
  qiankunWindow,
} from "vite-plugin-qiankun/dist/helper";
import { codeMap } from '../../../code';

export const useSendCode = (chapter) => {
  createEffect(() => {
    if (qiankunWindow && qiankunWindow.setGlobalState) {
      qiankunWindow?.setGlobalState({
        code: codeMap['solid'][chapter]
      })
    }
  })
}

// src/react/src/hooks/useSendCode.js
import { useEffect } from 'react';
import {
  qiankunWindow,
} from "vite-plugin-qiankun/dist/helper";
import { codeMap } from '../../../code';

export const useSendCode = (chapter) => {
  useEffect(() => {
    // todo 发数据
    if (qiankunWindow && qiankunWindow.setGlobalState) {
      qiankunWindow?.setGlobalState({
        code: codeMap['react'][chapter]
      })
    }
  }, []);
}
