// src/solid/src/pages/Chapter05.jsx
function SlotContainer1(props) {
  const { children } = props;
  return <div className="m-4 p-4 border rounded">{children}</div>;
}

function SlotContainer2(props) {
  const { header, footer, children } = props;
  return (
    <div className="m-4 p-4 border rounded">
      <header>{header}</header>
      <section>子组件原有内容</section>
      <section>{children}</section>
      <footer>{footer}</footer>
    </div>
  );
}

export default function Page() {
  return (
    <section>
      <h1>第五章 —— slot</h1>
      <SlotContainer1>hello world</SlotContainer1>
      <SlotContainer2 header={<span>父组件header</span>} footer="父组件footer">
        hello world2
      </SlotContainer2>
    </section>
  );
}

// src/svelte/src/pages/Chapter05.svelte
<script>
  import SlotContainer1 from './Chapter05_Child1.svelte';
  import SlotContainer2 from './Chapter05_Child2.svelte';
</script>

<section>
  <h1>第五章 —— slot</h1>
  <SlotContainer1>
    hello world
  </SlotContainer1>
  <SlotContainer2>
    hello world2
    <span slot="header">父组件header</span>
    <span slot="footer">父组件footer</span>
  </SlotContainer2>
</section>
