// src/vue/src/pages/Chapter06.vue
<template>
  <section>
    <h1>第六章 —— computed</h1>
    <button
        class="w-auto h-auto p-1 border"
        @click="updateCount"
      >
        +1
      </button>
      <span>
        {{count}}的2倍是：{{doubleCount}}
      </span>
  </section>
</template>

<script setup>
import { ref, computed } from 'vue';
import { useSendCode } from '../hooks/useSendCode';

let count = ref(0);
let doubleCount = computed(() => {
  return count.value * 2
});

const updateCount = () => {
  count.value++;
}

useSendCode('06');
</script>

// src/svelte/src/pages/Chapter06.svelte
<script>
  import { useSendCode } from '../hooks/useSendCode';

  let count = 0;

  $: doubleCount = count * 2;

  const updateCount = () => {
    count++;
  };

  useSendCode('06');
</script>

<section>
  <h1>第六章 —— computed</h1>
  <button class="w-auto h-auto p-1 border" on:click={updateCount}> +1 </button>
  <span>
    {count}的2倍是：{doubleCount}
  </span>
</section>
