// src/react/src/pages/Chapter08.jsx
import { useState } from "react";
import { useSendCode } from '../hooks/useSendCode';

export default function Page() {
  const [gender, setGender] = useState("");

  const changeGender = (e) => {
    setGender(e.target.value);
  };

  useSendCode('08');

  return (
    <section>
      <h1>第八章 —— if</h1>
      请选择性别：
      <section className="flex">
        <input
          id="male"
          type="radio"
          value="male"
          name="gender"
          checked={gender === "male"}
          onChange={changeGender}
        />
        <label htmlFor="male">男</label>
      </section>
      <section className="flex">
        <input
          id="female"
          type="radio"
          value="femail"
          name="gender"
          checked={gender === "female"}
          onChange={changeGender}
        />
        <label htmlFor="female">女</label>
      </section>
      {gender && (
        <section>
          你好，
          {gender === "male" ? (
            <span className="text-sky-400">先生</span>
          ) : (
            <span className="text-rose-400">女士</span>
          )}
        </section>
      )}
    </section>
  );
}

// src/svelte/src/pages/Chapter08.svelte
<script>
  import { useSendCode } from '../hooks/useSendCode';
  let gender = '';

  const changeGender = (e) => {
    gender = e.target.value;
  }
  useSendCode('08');
</script>
<section>
  <h1>第八章 —— if</h1>
  请选择性别：
  <section class="flex">
    <input
      id="male"
      type="radio"
      value="male"
      name="gender"
      checked={gender === "male"}
      on:change={changeGender}
    />
    <label for="male">男</label>
  </section>
  <section class="flex">
    <input
      id="female"
      type="radio"
      value="femail"
      name="gender"
      checked={gender === "female"}
      on:change={changeGender}
    />
    <label for="female">女</label>
  </section>
  {#if gender}
    <section>
      你好，
      {#if gender === 'male'}
        <span class="text-sky-400">先生</span>
      {:else}
        <span class="text-rose-400">女士</span>
      {/if}
    </section>
  {/if}
</section>
