// src/vue/src/pages/Chapter02.vue
<template>
  <section>
    <h1>第二章 —— 方法</h1>
    <div>
      count: {{count}}
      <button class="w-16 h-10 rounded-sm flex items-center justify-center border" @click="updateCount">+1</button>
    </div>
  </section>
</template>

<script setup>
  import { ref } from 'vue';
  import { useSendCode } from '../hooks/useSendCode';
  const count = ref(0);
  const updateCount = () => {
    count.value++;
  }

  useSendCode('02');
</script>

// src/svelte/src/pages/Chapter02.svelte
<script>
  import { useSendCode } from '../hooks/useSendCode';
  let count = 0;

  const updateCount = () => {
    count++;
  }
  useSendCode('02')
</script>

<section>
  <h1>第二章 —— 方法</h1>
  <div>
    count: {count}
    <button class="w-16 h-10 rounded-sm flex items-center justify-center border" on:click={updateCount}>+1</button>
  </div>
</section>
