// src/vue/src/pages/Chapter12.vue
<template>
  <section>
    <h1>第十二章 —— context</h1>
    <Child />
  </section>
</template>

<script>
  export const ContextKey = 'ThemeContext';
</script>
<script setup>
  import { ref, provide } from 'vue';
  import { useSendCode } from '../hooks/useSendCode';
  import Child from './Chapter12_Child1.vue';

  const text = 'hello world';
  const theme = ref('dark');

  const setTheme = (newTheme) => {
    theme.value = newTheme;
  }

  provide(ContextKey, {
    text,
    theme,
    setTheme
  });

  useSendCode('12');
</script>

// src/svelte/src/pages/Chapter12.svelte
<script context="module">
  export const ContextKey = 'ThemeContext'
</script>
<script>
  import { setContext } from 'svelte';
  import { writable } from 'svelte/store';
  import { useSendCode } from '../hooks/useSendCode';
  import Child from './Chapter12_Child1.svelte';

  let text = 'hello world';
  let theme = writable('dark');

  const setTheme = (newTheme) => {
    $theme = newTheme
  }

  setContext(ContextKey, {
    text,
    theme,
    setTheme
  });

  useSendCode('12');
</script>

<section>
  <h1>第十二章 —— context</h1>
  <Child />
</section>
