// src/react/src/pages/Chapter07.jsx
import { useEffect, useState } from 'react';
import { useSendCode } from '../hooks/useSendCode';

export default function Page() {
  const [count, setCount] = useState(0);

  useEffect(() => {
    console.log('count改变了');
  }, [count]);

  const updateCount = () => {
    setCount(count + 1);
  }

  useSendCode('07');

  return (
    <section>
      <h1>第七章 —— watch</h1>
      <button className="w-auto h-auto p-1 border" onClick={updateCount}>+1</button>
      <span>count: {count}</span>
    </section>
  )
}

// src/svelte/src/pages/Chapter07.svelte
<script>
  import { useSendCode } from '../hooks/useSendCode';
  let count = 0;
  let oldCount = count;
  
  $: if (count !== oldCount) {
    console.log('count改变了');
    oldCount = count;
  }

  const updateCount = () => {
    count++;
  }

  useSendCode('07')
</script>

<section>
  <h1>第七章 —— watch</h1>
  <button class="w-auto h-auto p-1 border" on:click={updateCount}>+1</button>
  <span>count: {count}</span>
</section>
