// src/vue/src/pages/Chapter07.vue
<template>
  <section>
    <h1>第七章 —— watch</h1>
    <button class="w-auto h-auto p-1 border" @click="updateCount">+1</button>
    <span>count: {{count}}</span>
  </section>
</template>

<script setup>
import { watch, ref } from "vue";
import { useSendCode } from '../hooks/useSendCode';

let count = ref(0);

const updateCount = () => {
  count.value++;
};

watch(
  () => count.value,
  () => {
    console.log("count改变了");
  }
);

useSendCode('07');
</script>

// src/svelte/src/pages/Chapter07.svelte
<script>
  import { useSendCode } from '../hooks/useSendCode';
  let count = 0;
  let oldCount = count;
  
  $: if (count !== oldCount) {
    console.log('count改变了');
    oldCount = count;
  }

  const updateCount = () => {
    count++;
  }

  useSendCode('07')
</script>

<section>
  <h1>第七章 —— watch</h1>
  <button class="w-auto h-auto p-1 border" on:click={updateCount}>+1</button>
  <span>count: {count}</span>
</section>
