// src/svelte/src/pages/Chapter03_Child.svelte
<script>
  import { createEventDispatcher } from "svelte";
  const dispatch = createEventDispatcher();

  export let name;

  const onClickFunc = () => {
    dispatch("sayHello");
  };
</script>

<div>
  <span>name: {name}</span>
  <button
    class="w-[120px] h-10 rounded-sm flex items-center justify-center border"
    on:click={onClickFunc}
  >调用父级方法</button>
</div>

// src/vue/src/pages/Chapter03_Child.vue
<template>
  <div>
    <span>name: {{ name }}</span>
    <button
      class="w-[120px] h-10 rounded-sm flex items-center justify-center border"
      @click="onClickFunc"
    >
      调用父级方法
    </button>
  </div>
</template>

<script setup>
import { ref } from "vue";
const props = defineProps(["name"]);
const name = ref(props.name);

const emit = defineEmits(["sayHello"]);

const onClickFunc = () => {
  emit("sayHello");
};
</script>
