// src/react/src/pages/Chapter01.jsx
import { useState, useEffect } from "react";

export default function Chapter01() {
  const [count] = useState(0);

  useEffect(() => {
    console.log('zzh 发送数据');
    window.microApp.dispatch({data: 'react第一章数据'});
  }, [])

  return (
    <section>
      <h1>第一章 —— 数据绑定</h1>
      <div>变量：{count}</div>
    </section>
  );
}

// src/vue/src/pages/Chapter01.vue
<template>
  <section>
    <h1>第一章 —— 变量</h1>
    <div>变量：{{ count }}</div>
  </section>
</template>

<script setup>
import { useRoute, useRouter } from 'vue-router';
import { ref, watch } from 'vue';
import { vueCode } from '../../../code/Chapter01';

const count = ref(0);
const route = useRoute();
const router = useRouter();
console.log('zzh route', route, router);

watch(() => route.path, () => {
  console.log('zzh route watch');
  window.microApp.dispatch({ data: vueCode });
})

</script>
